/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import POJO.NhanVien;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import DAO.NhanVienDAO;
import java.awt.Component;
import java.awt.Container;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Administrator
 */
public class Ql_NhanVien extends javax.swing.JFrame {

    /**
     * Creates new form Ql_NhanVien
     */
    Vector tblData = new Vector();
    Vector tblTitle = new Vector();
    DefaultTableModel tblModel;
    static ArrayList<NhanVien> dsnv = NhanVienDAO.getDSNV();

    
    public Ql_NhanVien() {
        initComponents();
        bangNhanVien();
        laydulieuNV(dsnv);
    }
    public void bangNhanVien(){
        tblTitle.add("Mã"); tblTitle.add("Họ tên"); tblTitle.add("Ngày sinh"); 
        tblTitle.add("Giới tính"); tblTitle.add("Địa chỉ"); tblTitle.add("Số điện thoại");
        tblTitle.add("Email"); tblTitle.add("Tài khoản"); tblTitle.add("Mật khẩu");
        tblTitle.add("Quyền"); tblTitle.add("Link ảnh"); 
    }
    public void laydulieuNV(ArrayList<NhanVien> dsnv){
        tblData.removeAllElements();
        for(NhanVien nv : dsnv){
            Vector v = new Vector();
            v.add(nv.getMa().trim()); v.add(nv.getTen().trim()); v.add(nv.getNgaysinhString().trim());
            v.add(nv.getGioitinhString().trim()); v.add(nv.getDiachiString().trim()); v.add(nv.getSdt().trim()); 
            v.add(nv.getEmail().trim()); v.add(nv.getTaikhoanString().trim()); v.add(nv.getMatkhauString().trim()); 
            v.add(nv.getQuyen().trim()); 
            if(nv.getHinhString() == null)
                 v.add("Rỗng");
            else
                v.add(nv.getHinhString());
            tblData.add(v);
        }
        tbl_NhanVien.setModel(new DefaultTableModel(tblData, tblTitle));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txt_MK = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_DC = new javax.swing.JTextArea();
        txt_TK = new javax.swing.JTextField();
        txt_Email = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_MaNV = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_TenNV = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_NS = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_SDT = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_Anh = new javax.swing.JTextField();
        btn_Browser = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        rdo_Nam = new javax.swing.JRadioButton();
        rdo_Nu = new javax.swing.JRadioButton();
        btn_Them = new javax.swing.JButton();
        btn_Xoa = new javax.swing.JButton();
        btn_Sua = new javax.swing.JButton();
        btn_LamMoi = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_NhanVien = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lbl_img = new javax.swing.JLabel();
        btn_TimTen = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txt_Quyen = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Tài khoản :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Email :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Địa chỉ :");

        txt_DC.setColumns(20);
        txt_DC.setRows(5);
        jScrollPane1.setViewportView(txt_DC);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Mật  khẩu :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Mã NV :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Tên NV :");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Ngày sinh :");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("SĐT :");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Ảnh :");

        btn_Browser.setText("Browser");
        btn_Browser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BrowserActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Giới tính :");

        buttonGroup1.add(rdo_Nam);
        rdo_Nam.setText("Nam");

        buttonGroup1.add(rdo_Nu);
        rdo_Nu.setText("Nữ");

        btn_Them.setText("Thêm");
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });

        btn_Xoa.setText("Xóa");
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });

        btn_Sua.setText("Sửa");
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });

        btn_LamMoi.setText("Làm mới");
        btn_LamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LamMoiActionPerformed(evt);
            }
        });

        tbl_NhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_NhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_NhanVienMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_NhanVien);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ảnh đại diện", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        lbl_img.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_img, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_img, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addContainerGap())
        );

        btn_TimTen.setText("Tìm tên");
        btn_TimTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimTenActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Quyền :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(23, 23, 23)
                                        .addComponent(txt_Quyen))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txt_Email, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                            .addComponent(txt_MK, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_TK, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane1))))
                                .addGap(21, 21, 21)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(btn_Them)
                                .addGap(18, 18, 18)
                                .addComponent(btn_Xoa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_Sua)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_LamMoi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_TimTen)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_Anh)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rdo_Nam)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rdo_Nu))
                                    .addComponent(txt_SDT, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabel8)
                                        .addGap(8, 8, 8))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_NS)
                                    .addComponent(txt_TenNV)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_MaNV))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_Browser)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(txt_TK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(txt_MaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txt_TenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(txt_NS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(rdo_Nam)
                                    .addComponent(rdo_Nu))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(txt_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(txt_Anh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_Browser)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txt_MK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txt_Quyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(58, 58, 58)))))))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Them)
                    .addComponent(btn_Xoa)
                    .addComponent(btn_Sua)
                    .addComponent(btn_LamMoi)
                    .addComponent(btn_TimTen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_NhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_NhanVienMouseClicked
        // TODO add your handling code here:
        String ma = tbl_NhanVien.getValueAt(tbl_NhanVien.getSelectedRow(), 0).toString();
        String hoten = tbl_NhanVien.getValueAt(tbl_NhanVien.getSelectedRow(), 1).toString();
        String nsinh = tbl_NhanVien.getValueAt(tbl_NhanVien.getSelectedRow(), 2).toString();
        String gioitinh = tbl_NhanVien.getValueAt(tbl_NhanVien.getSelectedRow(), 3).toString();
        String diachi = tbl_NhanVien.getValueAt(tbl_NhanVien.getSelectedRow(), 4).toString();
        String sdt = tbl_NhanVien.getValueAt(tbl_NhanVien.getSelectedRow(), 5).toString();
        String email = tbl_NhanVien.getValueAt(tbl_NhanVien.getSelectedRow(), 6).toString();
        String taikhoan = tbl_NhanVien.getValueAt(tbl_NhanVien.getSelectedRow(), 7).toString();
        String matkhau = tbl_NhanVien.getValueAt(tbl_NhanVien.getSelectedRow(), 8).toString();
        String quyen = tbl_NhanVien.getValueAt(tbl_NhanVien.getSelectedRow(), 9).toString();
        String hinh = tbl_NhanVien.getValueAt(tbl_NhanVien.getSelectedRow(), 10).toString();
        
        txt_TK.setText(taikhoan);
        txt_MK.setText(matkhau);
        txt_Email.setText(email);
        txt_DC.setText(diachi);
        txt_MaNV.setText(ma);
        txt_TenNV.setText(hoten);
        txt_SDT.setText(sdt);
        txt_NS.setText(nsinh);
        txt_Anh.setText(hinh);
        if(!txt_Anh.getText().equals(""))
        {
            ImageIcon imgicon = new ImageIcon(new ImageIcon(txt_Anh.getText()).getImage().getScaledInstance(90, 110, Image.SCALE_SMOOTH));
            lbl_img.setIcon(imgicon);
        }
        txt_Quyen.setText(quyen);
        if(gioitinh=="Nam"){
            rdo_Nu.setSelected(false);
            rdo_Nam.setSelected(true);
        }
        else{
            rdo_Nam.setSelected(false);
            rdo_Nu.setSelected(true);
        }
    }//GEN-LAST:event_tbl_NhanVienMouseClicked

    public void clearAllTextField(Container con)
    {
        for(Component c: con.getComponents()){
            if(c instanceof JTextField){
                JTextField f = (JTextField)c;
                f.setText("");
            }
            else if(c instanceof Container)
                clearAllTextField((Container)c);
        }
    }
    private void btn_LamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LamMoiActionPerformed
        // TODO add your handling code here:
        buttonGroup1.clearSelection();
        txt_DC.setText("");
        clearAllTextField(this.getContentPane());
        tbl_NhanVien.setRowSorter(null);
    }//GEN-LAST:event_btn_LamMoiActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        // TODO add your handling code here:
        if(tbl_NhanVien.getSelectedRowCount()==1)
        {
            if(JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa không?", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                String ma = txt_MaNV.getText().trim();
                
                String sql = "delete from NhanVien where MaNV = '"+ma+"'";
                if(NhanVienDAO.ThemXoaSua(sql)!=-1)
                {
                    dsnv = NhanVienDAO.getDSNV();
                    laydulieuNV(dsnv);
                    JOptionPane.showMessageDialog(this, "Xóa thành công !", "Thông báo", 1);
                }
                else
                    JOptionPane.showMessageDialog(this, "Dữ liệu này đang được sử dụng, không thể xóa", "Thông báo", 2);
                    
            }
        }else{
            if(tbl_NhanVien.getRowCount()==0)
                JOptionPane.showMessageDialog(this, "Bảng trống","Thông báo",2);
            else
                JOptionPane.showMessageDialog(this, "Chưa chọn dòng cần xóa","Thông báo",2);
        }
    }//GEN-LAST:event_btn_XoaActionPerformed

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        // TODO add your handling code here:
        if(tbl_NhanVien.getSelectedRowCount()==1)
        {
            if(JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn sửa không?", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                String ma = txt_MaNV.getText().trim();
                String hoten = txt_TenNV.getText().trim();
                String nsinh = txt_NS.getText().trim();
                String gioitinh = "";
                if(rdo_Nam.isSelected())
                    gioitinh = "Nam";
                if(rdo_Nu.isSelected())
                    gioitinh = "Nữ";
                String diachi = txt_DC.getText().trim();
                String sdt = txt_SDT.getText().trim();
                String email = txt_Email.getText().trim();
                String taikhoan = txt_TK.getText().trim();
                String matkhau = txt_MK.getText().trim();
                String quyen = txt_Quyen.getText().trim();
                String hinh = txt_Anh.getText().trim();
                
                String sql = "set dateformat dmy\n" +
                "update NhanVien set TenNV = N'"+hoten+"', NgaySinh = '"+nsinh+"', GioiTinh = N'"+gioitinh+"', \n" +
                "DiaChi = N'"+diachi+"', SDT = '"+sdt+"', Email = '"+email+"', HinhAnh = '"+hinh+"', TaiKhoan = '"+taikhoan+"', \n" +
                "MatKhau = '"+matkhau+"', Quyen = '"+quyen+"' where MaNV = '"+ma+"'";
                
                NhanVienDAO.ThemXoaSua(sql);
                dsnv = NhanVienDAO.getDSNV();
                laydulieuNV(dsnv);
                JOptionPane.showMessageDialog(this, "Sửa thành công !", "Thông báo", 1);
            }
        }else{
            if(tbl_NhanVien.getRowCount()==0)
                JOptionPane.showMessageDialog(this, "Bảng trống","Thông báo",2);
            else
                JOptionPane.showMessageDialog(this, "Chưa chọn dòng cần sửa","Thông báo",2);
        }
    }//GEN-LAST:event_btn_SuaActionPerformed

    private void btn_TimTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimTenActionPerformed
        // TODO add your handling code here:
        String ten = txt_TenNV.getText().trim().toLowerCase();
        DefaultTableModel tableModel = (DefaultTableModel)tbl_NhanVien.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(tableModel);
        tbl_NhanVien.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(ten));
    }//GEN-LAST:event_btn_TimTenActionPerformed

    private void btn_BrowserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BrowserActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser("C:\\");
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        txt_Anh.setText(filename);
        ImageIcon imgicon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(90, 110, Image.SCALE_SMOOTH));
        lbl_img.setIcon(imgicon);
    }//GEN-LAST:event_btn_BrowserActionPerformed

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn thêm không?", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            String ma = txt_MaNV.getText().trim();
            String hoten = txt_TenNV.getText().trim();
            String nsinh = txt_NS.getText().trim();
            String gioitinh = "";
            if(rdo_Nam.isSelected())
                gioitinh = "Nam";
            if(rdo_Nu.isSelected())
                gioitinh = "Nữ";
            String diachi = txt_DC.getText().trim();
            String sdt = txt_SDT.getText().trim();
            String email = txt_Email.getText().trim();
            String taikhoan = txt_TK.getText().trim();
            String matkhau = txt_MK.getText().trim();
            String quyen = txt_Quyen.getText().trim();
            String hinh = txt_Anh.getText().trim();
            
            String sql="set dateformat dmy\n" + "insert into NhanVien(MaNV, TenNV, NgaySinh, GioiTinh, DiaChi, SDT, Email, HinhAnh, TaiKhoan, MatKhau,Quyen) \n" +
            "values ('"+ma+"', N'"+hoten+"', '"+nsinh+"', N'"+gioitinh+"', N'"+diachi+"', '"+sdt+"', '"+email+"', '"+hinh+"', '"+taikhoan+"', '"+matkhau+"','"+quyen+"')";
            int kq=NhanVienDAO.ThemXoaSua(sql);
            if(kq!=-1)
            {
                dsnv = NhanVienDAO.getDSNV();
                laydulieuNV(dsnv);
                JOptionPane.showMessageDialog(this, "Thêm thành công !", "Thông báo",1);
            }
            else
                JOptionPane.showMessageDialog(this, "Mã NV này đã tồn tại, không thể thêm", "Thông báo", 2);
        }
    }//GEN-LAST:event_btn_ThemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ql_NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ql_NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ql_NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ql_NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ql_NhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Browser;
    private javax.swing.JButton btn_LamMoi;
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_TimTen;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lbl_img;
    private javax.swing.JRadioButton rdo_Nam;
    private javax.swing.JRadioButton rdo_Nu;
    private javax.swing.JTable tbl_NhanVien;
    private javax.swing.JTextField txt_Anh;
    private javax.swing.JTextArea txt_DC;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_MK;
    private javax.swing.JTextField txt_MaNV;
    private javax.swing.JTextField txt_NS;
    private javax.swing.JTextField txt_Quyen;
    private javax.swing.JTextField txt_SDT;
    private javax.swing.JTextField txt_TK;
    private javax.swing.JTextField txt_TenNV;
    // End of variables declaration//GEN-END:variables
}
