/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import POJO.SanPham;
import POJO.LoaiSP;
import DAO.SanPhamDAO;
import DAO.LoaiSPDAO;
import java.awt.Component;
import java.awt.Container;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Administrator
 */
public class QL_SanPham extends javax.swing.JFrame {

    /**
     * Creates new form QL_SanPham
     */
    Vector tblDataSP = new Vector();
    Vector tblTitleSP = new Vector();
    Vector tblDataLSP = new Vector();
    Vector tblTitleLSP = new Vector();
    DefaultTableModel tblModel;
    static ArrayList<SanPham> dssp = SanPhamDAO.getDSSP();
    static ArrayList<LoaiSP> dslsp = LoaiSPDAO.getDSLSP();
    public QL_SanPham() {
        initComponents();
        bangLSP();
        bangSP();
        laydulieuLSP(dslsp);
        laydulieuSP(dssp);
        setcbo_loaisp();
    }

    public void setcbo_loaisp(){
        for(LoaiSP i : dslsp){
            cbo_LoaiSP.addItem(i.getMaloai());
        }
    }
    public void bangSP(){
        tblTitleSP.add("Mã SP"); tblTitleSP.add("Tên SP"); tblTitleSP.add("Giá"); 
        tblTitleSP.add("Đơn vị tính"); tblTitleSP.add("Mã loại SP"); 
    }
    public void bangLSP(){
        tblTitleLSP.add("Mã loại SP"); tblTitleLSP.add("Tên loại SP"); 
    }
    public void laydulieuSP(ArrayList<SanPham> dssp){
        tblDataSP.removeAllElements();
        for(SanPham nv : dssp){
            Vector v = new Vector();
            v.add(nv.getMasp()); v.add(nv.getTensp()); v.add(nv.getGia());
            v.add(nv.getDvtS()); v.add(nv.getMalsp()); 
            tblDataSP.add(v);
        }
        tbl_SP.setModel(new DefaultTableModel(tblDataSP, tblTitleSP));
    }
    public void laydulieuLSP(ArrayList<LoaiSP> dslsp){
        tblDataLSP.removeAllElements();
        for(LoaiSP lsp : dslsp){
            Vector v = new Vector();
            v.add(lsp.getMaloai()); v.add(lsp.getTenloai());
            tblDataLSP.add(v);
        }
        tbl_LoaiSP.setModel(new DefaultTableModel(tblDataLSP, tblTitleLSP));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_LoaiSP = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btn_ThemLSP = new javax.swing.JButton();
        btn_XoaLSP = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_MaLSP = new javax.swing.JTextField();
        txt_TenLSP = new javax.swing.JTextField();
        btn_SuaLSP = new javax.swing.JButton();
        btn_LamMoiLSP = new javax.swing.JButton();
        btn_TimTenLSP = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_MSP = new javax.swing.JTextField();
        txt_TSP = new javax.swing.JTextField();
        txt_Gia = new javax.swing.JTextField();
        txt_DVT = new javax.swing.JTextField();
        cbo_LoaiSP = new javax.swing.JComboBox<>();
        btn_ThemSP = new javax.swing.JButton();
        btn_XoaSP = new javax.swing.JButton();
        btn_SuaSP = new javax.swing.JButton();
        btn_LamMoiSP = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_SP = new javax.swing.JTable();
        btn_TimTenSP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_LoaiSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_LoaiSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_LoaiSPMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_LoaiSP);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Mã loại SP :");

        btn_ThemLSP.setText("Thêm");
        btn_ThemLSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemLSPActionPerformed(evt);
            }
        });

        btn_XoaLSP.setText("Xóa");
        btn_XoaLSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaLSPActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Tên loại SP :");

        btn_SuaLSP.setText("Sửa");
        btn_SuaLSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaLSPActionPerformed(evt);
            }
        });

        btn_LamMoiLSP.setText("Làm mới");
        btn_LamMoiLSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LamMoiLSPActionPerformed(evt);
            }
        });

        btn_TimTenLSP.setText("Tìm tên");
        btn_TimTenLSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimTenLSPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(btn_ThemLSP))
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_TenLSP)
                                            .addComponent(txt_MaLSP))
                                        .addGap(97, 97, 97))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btn_XoaLSP)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_SuaLSP)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_LamMoiLSP)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_TimTenLSP)
                                        .addGap(0, 6, Short.MAX_VALUE)))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_MaLSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_TenLSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ThemLSP)
                    .addComponent(btn_XoaLSP)
                    .addComponent(btn_SuaLSP)
                    .addComponent(btn_LamMoiLSP)
                    .addComponent(btn_TimTenLSP))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Loại sản phẩm", jPanel1);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Mã SP:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Tên SP:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Giá:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Đơn vị tính:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Loại SP:");

        btn_ThemSP.setText("Thêm");
        btn_ThemSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemSPActionPerformed(evt);
            }
        });

        btn_XoaSP.setText("Xóa");
        btn_XoaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaSPActionPerformed(evt);
            }
        });

        btn_SuaSP.setText("Sửa");
        btn_SuaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaSPActionPerformed(evt);
            }
        });

        btn_LamMoiSP.setText("Làm mới");
        btn_LamMoiSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LamMoiSPActionPerformed(evt);
            }
        });

        tbl_SP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_SP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_SPMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_SP);

        btn_TimTenSP.setText("Tìm tên");
        btn_TimTenSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimTenSPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_ThemSP)
                        .addGap(18, 18, 18)
                        .addComponent(btn_XoaSP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_SuaSP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_LamMoiSP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_TimTenSP))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_Gia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_TSP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_MSP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_DVT, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                .addComponent(cbo_LoaiSP, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_MSP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_TSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_Gia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_DVT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbo_LoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ThemSP)
                    .addComponent(btn_XoaSP)
                    .addComponent(btn_SuaSP)
                    .addComponent(btn_LamMoiSP)
                    .addComponent(btn_TimTenSP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Sản phẩm", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ThemLSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemLSPActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn thêm không?", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                String ma = txt_MaLSP.getText().trim();
                String ten = txt_TenLSP.getText().trim();
                String sql = "insert into LoaiSanPham(MaLSP, TenLSP) values ('"+ma+"', N'"+ten+"')";
                int kq=LoaiSPDAO.ThemXoaSua(sql);
                if(kq!=-1)
                {
                    dslsp = LoaiSPDAO.getDSLSP();
                    laydulieuLSP(dslsp);
                    JOptionPane.showMessageDialog(this, "Thêm thành công !", "Thông báo",1);
                }
                else
                     JOptionPane.showMessageDialog(this, "Mã loại SP này đã tồn tại, không thể thêm", "Thông báo", 2);
                    
            }
    }//GEN-LAST:event_btn_ThemLSPActionPerformed

    private void btn_XoaLSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaLSPActionPerformed
        // TODO add your handling code here:
        if(tbl_LoaiSP.getSelectedRowCount()==1)
        {
            if(JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa không?", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                String ma = txt_MaLSP.getText().trim();
                String sql = "delete from LoaiSanPham where MaLSP = '"+ma+"'";
                if(LoaiSPDAO.ThemXoaSua(sql)!=-1)
                {
                     dslsp = LoaiSPDAO.getDSLSP();
                    laydulieuLSP(dslsp);
                    JOptionPane.showMessageDialog(this, "Xóa thành công !", "Thông báo", 1);
                }
                else
                    JOptionPane.showMessageDialog(this, "Dữ liệu này đang được sử dụng, không thể xóa", "Thông báo", 2);
                    
            }
        }else{
            if(tbl_LoaiSP.getRowCount()==0)
                JOptionPane.showMessageDialog(this, "Bảng trống","Thông báo",2);
            else
                JOptionPane.showMessageDialog(this, "Chưa chọn dòng cần xóa","Thông báo",2);
        }
    }//GEN-LAST:event_btn_XoaLSPActionPerformed

    private void btn_SuaLSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaLSPActionPerformed
        // TODO add your handling code here:
        if(tbl_LoaiSP.getSelectedRowCount()==1)
        {
            if(JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn sửa không?", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                    String ma = txt_MaLSP.getText().trim();
                    String ten = txt_TenLSP.getText().trim();
                    String sql = "update LoaiSanPham set TenLSP = N'"+ten+"' where MaLSP = '"+ma+"'";
                    LoaiSPDAO.ThemXoaSua(sql);
                    dslsp = LoaiSPDAO.getDSLSP();
                    laydulieuLSP(dslsp);
                    JOptionPane.showMessageDialog(this, "Sửa thành công !", "Thông báo", 1);
            }
        }else{
            if(tbl_LoaiSP.getRowCount()==0)
                JOptionPane.showMessageDialog(this, "Bảng trống","Thông báo",2);
            else
                JOptionPane.showMessageDialog(this, "Chưa chọn dòng cần sửa","Thông báo",2);
        }
    }//GEN-LAST:event_btn_SuaLSPActionPerformed

    public void clearAllTextField(Container con)
    {
        for(Component c: con.getComponents()){
            if(c instanceof JTextField){
                JTextField f = (JTextField)c;
                f.setText("");
            }
            else if(c instanceof Container)
                clearAllTextField((Container)c);
        }
    }
    private void btn_LamMoiLSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LamMoiLSPActionPerformed
        // TODO add your handling code here:
        clearAllTextField(this.getContentPane());
        tbl_LoaiSP.setRowSorter(null);
    }//GEN-LAST:event_btn_LamMoiLSPActionPerformed

    private void btn_TimTenLSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimTenLSPActionPerformed
        // TODO add your handling code here:
        String ten = txt_TenLSP.getText().trim().toLowerCase();
        DefaultTableModel tableModel = (DefaultTableModel)tbl_LoaiSP.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(tableModel);
        tbl_LoaiSP.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(ten));
    }//GEN-LAST:event_btn_TimTenLSPActionPerformed

    private void tbl_LoaiSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_LoaiSPMouseClicked
        // TODO add your handling code here:
        String ma = tbl_LoaiSP.getValueAt(tbl_LoaiSP.getSelectedRow(), 0).toString();
        String ten = tbl_LoaiSP.getValueAt(tbl_LoaiSP.getSelectedRow(), 1).toString();
        
        
        txt_MaLSP.setText(ma);
        txt_TenLSP.setText(ten);
    }//GEN-LAST:event_tbl_LoaiSPMouseClicked

    private void btn_ThemSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemSPActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn thêm không?", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                String ma = txt_MSP.getText().trim();
                String ten = txt_TSP.getText().trim();
                int gia = Integer.parseInt(txt_Gia.getText().trim());
                String dvt = txt_DVT.getText().trim();
                String maLSP = cbo_LoaiSP.getSelectedItem().toString();
                String sql = "insert into SanPham(MaSP, TenSP, GiaTien, DVT, MaLSP) values ('"+ma+"', N'"+ten+"', "+gia+", N'"+dvt+"', '"+maLSP+"')";
                int kq=SanPhamDAO.ThemXoaSua(sql);
                if(kq!=-1)
                {
                    dssp = SanPhamDAO.getDSSP();
                    laydulieuSP(dssp);
                    JOptionPane.showMessageDialog(this, "Thêm thành công !", "Thông báo",1);
                }
                else
                     JOptionPane.showMessageDialog(this, "Mã SP này đã tồn tại, không thể thêm", "Thông báo", 2);
                    
            }
    }//GEN-LAST:event_btn_ThemSPActionPerformed

    private void btn_XoaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaSPActionPerformed
        // TODO add your handling code here:
        if(tbl_SP.getSelectedRowCount()==1)
        {
            if(JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa không?", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                String ma = txt_MSP.getText().trim();
                String sql = "delete from SanPham where MaSP = '"+ma+"'";
                if(SanPhamDAO.ThemXoaSua(sql)!=-1)
                {
                     dssp = SanPhamDAO.getDSSP();
                    laydulieuSP(dssp);
                    JOptionPane.showMessageDialog(this, "Xóa thành công !", "Thông báo", 1);
                }
                else
                    JOptionPane.showMessageDialog(this, "Dữ liệu này đang được sử dụng, không thể xóa", "Thông báo", 2);
                    
            }
        }else{
            if(tbl_SP.getRowCount()==0)
                JOptionPane.showMessageDialog(this, "Bảng trống","Thông báo",2);
            else
                JOptionPane.showMessageDialog(this, "Chưa chọn dòng cần xóa","Thông báo",2);
        }
    }//GEN-LAST:event_btn_XoaSPActionPerformed

    private void btn_SuaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaSPActionPerformed
        // TODO add your handling code here:
        if(tbl_SP.getSelectedRowCount()==1)
        {
            if(JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn sửa không?", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                    String ma = txt_MSP.getText().trim();
                    String ten = txt_TSP.getText().trim();
                    int gia = Integer.parseInt(txt_Gia.getText().trim());
                    String dvt = txt_DVT.getText().trim();
                    String maLSP = cbo_LoaiSP.getSelectedItem().toString();
                    String sql = "update SanPham set TenSP = N'"+ten+"', GiaTien = "+gia+", DVT = N'"+dvt+"', MaLSP= '"+maLSP+"' where MaSP = '"+ma+"'";
                    SanPhamDAO.ThemXoaSua(sql);
                    dssp = SanPhamDAO.getDSSP();
                    laydulieuSP(dssp);
                    JOptionPane.showMessageDialog(this, "Sửa thành công !", "Thông báo", 1);
            }
        }else{
            if(tbl_SP.getRowCount()==0)
                JOptionPane.showMessageDialog(this, "Bảng trống","Thông báo",2);
            else
                JOptionPane.showMessageDialog(this, "Chưa chọn dòng cần sửa","Thông báo",2);
        }
    }//GEN-LAST:event_btn_SuaSPActionPerformed

    private void btn_LamMoiSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LamMoiSPActionPerformed
        // TODO add your handling code here:
        clearAllTextField(this.getContentPane());
        cbo_LoaiSP.setSelectedIndex(0);
        tbl_SP.setRowSorter(null);
    }//GEN-LAST:event_btn_LamMoiSPActionPerformed

    private void btn_TimTenSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimTenSPActionPerformed
        // TODO add your handling code here:
        String ten = txt_TSP.getText().trim().toLowerCase();
        DefaultTableModel tableModel = (DefaultTableModel)tbl_SP.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(tableModel);
        tbl_SP.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(ten));
    }//GEN-LAST:event_btn_TimTenSPActionPerformed

    private void tbl_SPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_SPMouseClicked
        // TODO add your handling code here:
        String ma = tbl_SP.getValueAt(tbl_SP.getSelectedRow(), 0).toString();
        String ten = tbl_SP.getValueAt(tbl_SP.getSelectedRow(), 1).toString();
        String gia = tbl_SP.getValueAt(tbl_SP.getSelectedRow(), 2).toString();
        String dvt = tbl_SP.getValueAt(tbl_SP.getSelectedRow(), 3).toString();
        String maLSP = tbl_SP.getValueAt(tbl_SP.getSelectedRow(), 4).toString();
        
        txt_MSP.setText(ma);
        txt_TSP.setText(ten);
        txt_Gia.setText(gia);
        txt_DVT.setText(dvt);
        cbo_LoaiSP.setSelectedItem(maLSP);
    }//GEN-LAST:event_tbl_SPMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QL_SanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QL_SanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QL_SanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QL_SanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QL_SanPham().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_LamMoiLSP;
    private javax.swing.JButton btn_LamMoiSP;
    private javax.swing.JButton btn_SuaLSP;
    private javax.swing.JButton btn_SuaSP;
    private javax.swing.JButton btn_ThemLSP;
    private javax.swing.JButton btn_ThemSP;
    private javax.swing.JButton btn_TimTenLSP;
    private javax.swing.JButton btn_TimTenSP;
    private javax.swing.JButton btn_XoaLSP;
    private javax.swing.JButton btn_XoaSP;
    private javax.swing.JComboBox<String> cbo_LoaiSP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tbl_LoaiSP;
    private javax.swing.JTable tbl_SP;
    private javax.swing.JTextField txt_DVT;
    private javax.swing.JTextField txt_Gia;
    private javax.swing.JTextField txt_MSP;
    private javax.swing.JTextField txt_MaLSP;
    private javax.swing.JTextField txt_TSP;
    private javax.swing.JTextField txt_TenLSP;
    // End of variables declaration//GEN-END:variables
}
